default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todolist_development
test:
  <<: *default
  database: todolist_test
production:
  <<: *default
  database: todolist_production
  username: postgres
  password: <%= ENV["TODOLIST_DATABASE_PASSWORD"] %>
